名字: 'run'

on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - 名字: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7

      - 名字: requirements
        run : pip3 install -r requirements.txt

      - 名字: main
        env:
          cookie_javbus: ${{ secrets.cookie_javbus }}
        run: |
          python3 ../javbus/javbus.py
          
